package com.campus.mapper;

import com.campus.model.ClassWeek;
import com.campus.model.ClassWeekKey;



public interface ClassWeekMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_week
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ClassWeekKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_week
     *
     * @mbggenerated
     */
    int insert(ClassWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_week
     *
     * @mbggenerated
     */
    int insertSelective(ClassWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_week
     *
     * @mbggenerated
     */
    ClassWeek selectByPrimaryKey(ClassWeekKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_week
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClassWeek record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_week
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClassWeek record);
}