package com.campus.mapper;

import com.campus.model.ClassSchedule;
import com.campus.model.ClassScheduleKey;

import java.util.List;


public interface ClassScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_schedule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ClassScheduleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_schedule
     *
     * @mbggenerated
     */
    int insert(ClassSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_schedule
     *
     * @mbggenerated
     */
    int insertSelective(ClassSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_schedule
     *
     * @mbggenerated
     */
    ClassSchedule selectByPrimaryKey(ClassScheduleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClassSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_schedule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClassSchedule record);

    int insertList(List list);
    List selectClassSchedule(ClassSchedule record);
    int deleteAccount(String account);
}