package com.campus.mapper;

import com.campus.model.ClassUpdate;
import com.campus.model.ClassUpdateKey;


public interface ClassUpdateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_update
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ClassUpdateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_update
     *
     * @mbggenerated
     */
    int insert(ClassUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_update
     *
     * @mbggenerated
     */
    int insertSelective(ClassUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_update
     *
     * @mbggenerated
     */
    ClassUpdate selectByPrimaryKey(ClassUpdateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_update
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClassUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_update
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClassUpdate record);

    ClassUpdate selectFirst(String account);
}