package com.campus.mapper;

import com.campus.model.EmptyClassroom;
import com.campus.model.EmptyClassroomKey;

import java.util.Date;
import java.util.List;


public interface EmptyClassroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empty_classroom
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(EmptyClassroomKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empty_classroom
     *
     * @mbggenerated
     */
    int insert(EmptyClassroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empty_classroom
     *
     * @mbggenerated
     */
    int insertSelective(EmptyClassroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empty_classroom
     *
     * @mbggenerated
     */
    EmptyClassroom selectByPrimaryKey(EmptyClassroomKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empty_classroom
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmptyClassroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table empty_classroom
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EmptyClassroom record);

    int deleteDefiniteDay(Date EmptyDay);


    int insertList(List list);
    List selectEmptyClassroom(EmptyClassroom emptyClassroom);
}