package com.campus.mapper;

import com.campus.model.JwxtInfo;


public interface JwxtInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jwxt_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jwxt_info
     *
     * @mbggenerated
     */
    int insert(JwxtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jwxt_info
     *
     * @mbggenerated
     */
    int insertSelective(JwxtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jwxt_info
     *
     * @mbggenerated
     */
    JwxtInfo selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jwxt_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JwxtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jwxt_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JwxtInfo record);
}