package com.campus.mapper;

import com.campus.model.PersonInfo;

public interface PersonInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbggenerated
     */
    int insert(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbggenerated
     */
    int insertSelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbggenerated
     */
    PersonInfo selectByPrimaryKey(String account);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PersonInfo record);
}