package com.campus.mapper;

import com.campus.model.ScoreData;
import com.campus.model.ScoreDataKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ScoreDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ScoreDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_data
     *
     * @mbggenerated
     */
    int insert(ScoreData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_data
     *
     * @mbggenerated
     */
    int insertSelective(ScoreData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_data
     *
     * @mbggenerated
     */
    ScoreData selectByPrimaryKey(ScoreDataKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScoreData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScoreData record);


    int insertList(List list);
    List selectScoreData(@Param("account") String account, @Param("termRange") String termRange);
}