package com.campus.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;
@JsonIgnoreProperties({"creationTime"})
public class ClassUpdate extends ClassUpdateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_update.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_update.creation_time
     *
     * @return the value of class_update.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_update.creation_time
     *
     * @param creationTime the value for class_update.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
}