package com.campus.model;

import java.io.Serializable;

public class ClassScheduleKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.week_number
     *
     * @mbggenerated
     */
    private String weekNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.term_range
     *
     * @mbggenerated
     */
    private String termRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.course_name
     *
     * @mbggenerated
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.place
     *
     * @mbggenerated
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.course_number
     *
     * @mbggenerated
     */
    private String courseNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.account
     *
     * @return the value of class_schedule.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.account
     *
     * @param account the value for class_schedule.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.week_number
     *
     * @return the value of class_schedule.week_number
     *
     * @mbggenerated
     */
    public String getWeekNumber() {
        return weekNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.week_number
     *
     * @param weekNumber the value for class_schedule.week_number
     *
     * @mbggenerated
     */
    public void setWeekNumber(String weekNumber) {
        this.weekNumber = weekNumber == null ? null : weekNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.term_range
     *
     * @return the value of class_schedule.term_range
     *
     * @mbggenerated
     */
    public String getTermRange() {
        return termRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.term_range
     *
     * @param termRange the value for class_schedule.term_range
     *
     * @mbggenerated
     */
    public void setTermRange(String termRange) {
        this.termRange = termRange == null ? null : termRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.course_name
     *
     * @return the value of class_schedule.course_name
     *
     * @mbggenerated
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.course_name
     *
     * @param courseName the value for class_schedule.course_name
     *
     * @mbggenerated
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.place
     *
     * @return the value of class_schedule.place
     *
     * @mbggenerated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.place
     *
     * @param place the value for class_schedule.place
     *
     * @mbggenerated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.course_number
     *
     * @return the value of class_schedule.course_number
     *
     * @mbggenerated
     */
    public String getCourseNumber() {
        return courseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.course_number
     *
     * @param courseNumber the value for class_schedule.course_number
     *
     * @mbggenerated
     */
    public void setCourseNumber(String courseNumber) {
        this.courseNumber = courseNumber == null ? null : courseNumber.trim();
    }
}