package com.campus.model;

public class ClassWeekKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_week.term_range
     *
     * @mbggenerated
     */
    private String termRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_week.week_number
     *
     * @mbggenerated
     */
    private String weekNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_week.term_range
     *
     * @return the value of class_week.term_range
     *
     * @mbggenerated
     */
    public String getTermRange() {
        return termRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_week.term_range
     *
     * @param termRange the value for class_week.term_range
     *
     * @mbggenerated
     */
    public void setTermRange(String termRange) {
        this.termRange = termRange == null ? null : termRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_week.week_number
     *
     * @return the value of class_week.week_number
     *
     * @mbggenerated
     */
    public String getWeekNumber() {
        return weekNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_week.week_number
     *
     * @param weekNumber the value for class_week.week_number
     *
     * @mbggenerated
     */
    public void setWeekNumber(String weekNumber) {
        this.weekNumber = weekNumber == null ? null : weekNumber.trim();
    }
}