package com.campus.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;
@JsonIgnoreProperties({"creationTime"})
public class ClassWeek extends ClassWeekKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_week.class_start
     *
     * @mbggenerated
     */
    private Date classStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_week.class_end
     *
     * @mbggenerated
     */
    private Date classEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_week.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_week.class_start
     *
     * @return the value of class_week.class_start
     *
     * @mbggenerated
     */
    public Date getClassStart() {
        return classStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_week.class_start
     *
     * @param classStart the value for class_week.class_start
     *
     * @mbggenerated
     */
    public void setClassStart(Date classStart) {
        this.classStart = classStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_week.class_end
     *
     * @return the value of class_week.class_end
     *
     * @mbggenerated
     */
    public Date getClassEnd() {
        return classEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_week.class_end
     *
     * @param classEnd the value for class_week.class_end
     *
     * @mbggenerated
     */
    public void setClassEnd(Date classEnd) {
        this.classEnd = classEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_week.creation_time
     *
     * @return the value of class_week.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_week.creation_time
     *
     * @param creationTime the value for class_week.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
}