package com.campus.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;
@JsonIgnoreProperties({"creationTime"})
public class ClassSchedule extends ClassScheduleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.teacher
     *
     * @mbggenerated
     */
    private String teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.week_range
     *
     * @mbggenerated
     */
    private String weekRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.week_type
     *
     * @mbggenerated
     */
    private String weekType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.session_start
     *
     * @mbggenerated
     */
    private String sessionStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.session_end
     *
     * @mbggenerated
     */
    private String sessionEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_schedule.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.teacher
     *
     * @return the value of class_schedule.teacher
     *
     * @mbggenerated
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.teacher
     *
     * @param teacher the value for class_schedule.teacher
     *
     * @mbggenerated
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.week_range
     *
     * @return the value of class_schedule.week_range
     *
     * @mbggenerated
     */
    public String getWeekRange() {
        return weekRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.week_range
     *
     * @param weekRange the value for class_schedule.week_range
     *
     * @mbggenerated
     */
    public void setWeekRange(String weekRange) {
        this.weekRange = weekRange == null ? null : weekRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.week_type
     *
     * @return the value of class_schedule.week_type
     *
     * @mbggenerated
     */
    public String getWeekType() {
        return weekType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.week_type
     *
     * @param weekType the value for class_schedule.week_type
     *
     * @mbggenerated
     */
    public void setWeekType(String weekType) {
        this.weekType = weekType == null ? null : weekType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.session_start
     *
     * @return the value of class_schedule.session_start
     *
     * @mbggenerated
     */
    public String getSessionStart() {
        return sessionStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.session_start
     *
     * @param sessionStart the value for class_schedule.session_start
     *
     * @mbggenerated
     */
    public void setSessionStart(String sessionStart) {
        this.sessionStart = sessionStart == null ? null : sessionStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.session_end
     *
     * @return the value of class_schedule.session_end
     *
     * @mbggenerated
     */
    public String getSessionEnd() {
        return sessionEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.session_end
     *
     * @param sessionEnd the value for class_schedule.session_end
     *
     * @mbggenerated
     */
    public void setSessionEnd(String sessionEnd) {
        this.sessionEnd = sessionEnd == null ? null : sessionEnd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_schedule.creation_time
     *
     * @return the value of class_schedule.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_schedule.creation_time
     *
     * @param creationTime the value for class_schedule.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
}