package com.campus.model;

import java.io.Serializable;
import java.util.Date;

public class ClassroomUpdateKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_update.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classroom_update.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_update.creation_time
     *
     * @return the value of classroom_update.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_update.creation_time
     *
     * @param creationTime the value for classroom_update.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classroom_update.openid
     *
     * @return the value of classroom_update.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classroom_update.openid
     *
     * @param openid the value for classroom_update.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }
}