package com.campus.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;
@JsonIgnoreProperties({"creationTime","classroomNumber","creationTime"})
public class EmptyClassroom extends EmptyClassroomKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empty_classroom.classroom_number
     *
     * @mbggenerated
     */
    private String classroomNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empty_classroom.classroom_capacity
     *
     * @mbggenerated
     */
    private String classroomCapacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empty_classroom.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empty_classroom.classroom_number
     *
     * @return the value of empty_classroom.classroom_number
     *
     * @mbggenerated
     */
    public String getClassroomNumber() {
        return classroomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empty_classroom.classroom_number
     *
     * @param classroomNumber the value for empty_classroom.classroom_number
     *
     * @mbggenerated
     */
    public void setClassroomNumber(String classroomNumber) {
        this.classroomNumber = classroomNumber == null ? null : classroomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empty_classroom.classroom_capacity
     *
     * @return the value of empty_classroom.classroom_capacity
     *
     * @mbggenerated
     */
    public String getClassroomCapacity() {
        return classroomCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empty_classroom.classroom_capacity
     *
     * @param classroomCapacity the value for empty_classroom.classroom_capacity
     *
     * @mbggenerated
     */
    public void setClassroomCapacity(String classroomCapacity) {
        this.classroomCapacity = classroomCapacity == null ? null : classroomCapacity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empty_classroom.creation_time
     *
     * @return the value of empty_classroom.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empty_classroom.creation_time
     *
     * @param creationTime the value for empty_classroom.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
}