package com.campus.model;

import java.io.Serializable;
import java.util.Date;

public class EmptyClassroomKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empty_classroom.empty_date
     *
     * @mbggenerated
     */
    private Date emptyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empty_classroom.empty_time
     *
     * @mbggenerated
     */
    private String emptyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empty_classroom.campus_type
     *
     * @mbggenerated
     */
    private String campusType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empty_classroom.classroom_building
     *
     * @mbggenerated
     */
    private String classroomBuilding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column empty_classroom.classroom_name
     *
     * @mbggenerated
     */
    private String classroomName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empty_classroom.empty_date
     *
     * @return the value of empty_classroom.empty_date
     *
     * @mbggenerated
     */
    public Date getEmptyDate() {
        return emptyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empty_classroom.empty_date
     *
     * @param emptyDate the value for empty_classroom.empty_date
     *
     * @mbggenerated
     */
    public void setEmptyDate(Date emptyDate) {
        this.emptyDate = emptyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empty_classroom.empty_time
     *
     * @return the value of empty_classroom.empty_time
     *
     * @mbggenerated
     */
    public String getEmptyTime() {
        return emptyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empty_classroom.empty_time
     *
     * @param emptyTime the value for empty_classroom.empty_time
     *
     * @mbggenerated
     */
    public void setEmptyTime(String emptyTime) {
        this.emptyTime = emptyTime == null ? null : emptyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empty_classroom.campus_type
     *
     * @return the value of empty_classroom.campus_type
     *
     * @mbggenerated
     */
    public String getCampusType() {
        return campusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empty_classroom.campus_type
     *
     * @param campusType the value for empty_classroom.campus_type
     *
     * @mbggenerated
     */
    public void setCampusType(String campusType) {
        this.campusType = campusType == null ? null : campusType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empty_classroom.classroom_building
     *
     * @return the value of empty_classroom.classroom_building
     *
     * @mbggenerated
     */
    public String getClassroomBuilding() {
        return classroomBuilding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empty_classroom.classroom_building
     *
     * @param classroomBuilding the value for empty_classroom.classroom_building
     *
     * @mbggenerated
     */
    public void setClassroomBuilding(String classroomBuilding) {
        this.classroomBuilding = classroomBuilding == null ? null : classroomBuilding.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column empty_classroom.classroom_name
     *
     * @return the value of empty_classroom.classroom_name
     *
     * @mbggenerated
     */
    public String getClassroomName() {
        return classroomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column empty_classroom.classroom_name
     *
     * @param classroomName the value for empty_classroom.classroom_name
     *
     * @mbggenerated
     */
    public void setClassroomName(String classroomName) {
        this.classroomName = classroomName == null ? null : classroomName.trim();
    }
}