package com.campus.model;

public class JwxtInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jwxt_info.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jwxt_info.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jwxt_info.openid
     *
     * @return the value of jwxt_info.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jwxt_info.openid
     *
     * @param openid the value for jwxt_info.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jwxt_info.account
     *
     * @return the value of jwxt_info.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jwxt_info.account
     *
     * @param account the value for jwxt_info.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }
}