package com.campus.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;
@JsonIgnoreProperties({"creationTime","updateTime"})
public class PersonInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.profession
     *
     * @mbggenerated
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.enrollment_date
     *
     * @mbggenerated
     */
    private String enrollmentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.clbum
     *
     * @mbggenerated
     */
    private String clbum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.grade
     *
     * @mbggenerated
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person_info.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.account
     *
     * @return the value of person_info.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.account
     *
     * @param account the value for person_info.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.name
     *
     * @return the value of person_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.name
     *
     * @param name the value for person_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.sex
     *
     * @return the value of person_info.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.sex
     *
     * @param sex the value for person_info.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.department
     *
     * @return the value of person_info.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.department
     *
     * @param department the value for person_info.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.profession
     *
     * @return the value of person_info.profession
     *
     * @mbggenerated
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.profession
     *
     * @param profession the value for person_info.profession
     *
     * @mbggenerated
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.enrollment_date
     *
     * @return the value of person_info.enrollment_date
     *
     * @mbggenerated
     */
    public String getEnrollmentDate() {
        return enrollmentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.enrollment_date
     *
     * @param enrollmentDate the value for person_info.enrollment_date
     *
     * @mbggenerated
     */
    public void setEnrollmentDate(String enrollmentDate) {
        this.enrollmentDate = enrollmentDate == null ? null : enrollmentDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.clbum
     *
     * @return the value of person_info.clbum
     *
     * @mbggenerated
     */
    public String getClbum() {
        return clbum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.clbum
     *
     * @param clbum the value for person_info.clbum
     *
     * @mbggenerated
     */
    public void setClbum(String clbum) {
        this.clbum = clbum == null ? null : clbum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.grade
     *
     * @return the value of person_info.grade
     *
     * @mbggenerated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.grade
     *
     * @param grade the value for person_info.grade
     *
     * @mbggenerated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.update_time
     *
     * @return the value of person_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.update_time
     *
     * @param updateTime the value for person_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person_info.creation_time
     *
     * @return the value of person_info.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person_info.creation_time
     *
     * @param creationTime the value for person_info.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
}