package com.campus.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;
@JsonIgnoreProperties({"creationTime"})
public class ScoreData extends ScoreDataKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_data.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_data.exam_type
     *
     * @mbggenerated
     */
    private String examType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_data.score
     *
     * @mbggenerated
     */
    private String score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_data.hour_credit
     *
     * @mbggenerated
     */
    private String hourCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_data.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score_data.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_data.name
     *
     * @return the value of score_data.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_data.name
     *
     * @param name the value for score_data.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_data.exam_type
     *
     * @return the value of score_data.exam_type
     *
     * @mbggenerated
     */
    public String getExamType() {
        return examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_data.exam_type
     *
     * @param examType the value for score_data.exam_type
     *
     * @mbggenerated
     */
    public void setExamType(String examType) {
        this.examType = examType == null ? null : examType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_data.score
     *
     * @return the value of score_data.score
     *
     * @mbggenerated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_data.score
     *
     * @param score the value for score_data.score
     *
     * @mbggenerated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_data.hour_credit
     *
     * @return the value of score_data.hour_credit
     *
     * @mbggenerated
     */
    public String getHourCredit() {
        return hourCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_data.hour_credit
     *
     * @param hourCredit the value for score_data.hour_credit
     *
     * @mbggenerated
     */
    public void setHourCredit(String hourCredit) {
        this.hourCredit = hourCredit == null ? null : hourCredit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_data.update_time
     *
     * @return the value of score_data.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_data.update_time
     *
     * @param updateTime the value for score_data.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score_data.creation_time
     *
     * @return the value of score_data.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score_data.creation_time
     *
     * @param creationTime the value for score_data.creation_time
     *
     * @mbggenerated
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }
}