package com.campus.model;

import java.io.Serializable;

public class TermKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.term_range
     *
     * @mbggenerated
     */
    private String termRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column term.term_type
     *
     * @mbggenerated
     */
    private String termType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.term_range
     *
     * @return the value of term.term_range
     *
     * @mbggenerated
     */
    public String getTermRange() {
        return termRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.term_range
     *
     * @param termRange the value for term.term_range
     *
     * @mbggenerated
     */
    public void setTermRange(String termRange) {
        this.termRange = termRange == null ? null : termRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column term.term_type
     *
     * @return the value of term.term_type
     *
     * @mbggenerated
     */
    public String getTermType() {
        return termType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column term.term_type
     *
     * @param termType the value for term.term_type
     *
     * @mbggenerated
     */
    public void setTermType(String termType) {
        this.termType = termType == null ? null : termType.trim();
    }
}